'use strict';

const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const output = path.join(root, 'public');
const marker = path.join(output, '.hcp-static-output');
const webDirectories = ['html', 'css', 'js', 'imgs'];

// Only the generated public directory may be replaced on subsequent builds.
if (path.dirname(output) !== root || path.basename(output) !== 'public') {
  throw new Error('Unexpected static output directory.');
}
for (const directory of webDirectories) {
  if (!fs.statSync(path.join(root, directory)).isDirectory()) {
    throw new Error(`Missing web directory: ${directory}`);
  }
}
if (fs.existsSync(output)) {
  if (!fs.existsSync(marker) && fs.readdirSync(output).length !== 0) {
    throw new Error('public already exists without the HCP build marker; refusing to replace it.');
  }
  // Vercel can upload an ignored directory as an empty placeholder.
  // Reuse an empty directory; only replace an output identified by our marker.
  if (fs.existsSync(marker)) fs.rmSync(output, { recursive: true });
}
fs.mkdirSync(output, { recursive: true });
fs.writeFileSync(marker, 'Generated by scripts/build-static.cjs\n');
// Static-host metadata: keep the local safety marker private and preserve .html URLs.
fs.writeFileSync(path.join(output, '.assetsignore'), '.hcp-static-output\n.assetsignore\n');
fs.writeFileSync(path.join(output, '_redirects'), '/ /html/login.html 302\n');
for (const directory of webDirectories) {
  fs.cpSync(path.join(root, directory), path.join(output, directory), { recursive: true });
}
fs.writeFileSync(path.join(output, 'index.html'), `<!doctype html>
<html lang="pt-BR"><head><meta charset="utf-8">
<meta http-equiv="refresh" content="0; url=html/login.html">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="icon" type="image/png" href="imgs/favicon.png">
<title>HCP</title></head><body><p><a href="html/login.html">Acessar o HCP</a></p></body></html>
`);
console.log(`Static HCP site ready: ${output}`);
console.log('Included: html, css, js, imgs and the root entry point.');
